
2022-11-17-15.31.30.538461+330 I1E1921               LEVEL: Event
PID     : 6206                 TID : 140204587792192 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, RAS/PD component, pdLogInternal, probe:120
START   : New Diagnostic Log file
DATA #1 : Build Level, 248 bytes
Instance "DB2" uses "64" bits and DB2 code release "SQL11056"
with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_13806", "DYN2201171140AMD64_13806", Fix Pack "0".
DATA #2 : System Info, 664 bytes
System: Linux vishnu-82ey 15 5 x86_64
CPU: total:16 online:12 Cores per socket:12 Threading degree per core:1 SIMD:Y CPU Features:SSE2,SSE3,SSSE3,SSE4,AVX2
CPU binding: not in use
CPU cache: L2:524288 bytes (shared by 2 threads) L3:4194304 bytes (shared by 6 threads)
Physical Memory(MB): total:7311 free:750
Virtual  Memory(MB): total:7311 free:750
Swap     Memory(MB): total:0 free:0
Kernel   Params: msgMaxMessageSize:8192 msgMsgMap:16384 msgMaxQueueIDs:32000
                 msgNumberOfHeaders:16384 msgMaxQueueSize:16384
                 msgMaxSegmentSize:16 shmMax:9223372036854775807 shmMin:1
                 shmIDs:4096 shmSegments:4096 semMap:1024000000 semIDs:32000
                 semNum:1024000000 semUndo:1024000000 semNumPerID:32000
                 semOps:500 semUndoSize:20 semMaxVal:32767
                 semAdjustOnExit:32767
Cur cpu time limit (seconds)  = 0xFFFFFFFFFFFFFFFF
Cur file size limit (bytes) = 0xFFFFFFFFFFFFFFFF
Cur data size (bytes)  = 0xFFFFFFFFFFFFFFFF
Cur stack size (bytes)  = 0x0000000000800000
Cur core size (bytes)  = 0xFFFFFFFFFFFFFFFF
Cur memory size (bytes) = 0xFFFFFFFFFFFFFFFF
nofiles (descriptors)  = 0x0000000000080000
Cur maximum number of processes = 0x00000000000071FA
Disk: 4K Device Support: NONE

Information in this record is only valid at the time when this file was
created (see this record's time stamp)

2022-11-17-15.31.30.555978+330 I1923E331             LEVEL: Error
PID     : 6206                 TID : 140204587792192 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.17.443453+330 I2255E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.18.939988+330 I2587E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.20.529034+330 I2919E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.22.915714+330 I3251E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.22.918530+330 I3583E425             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-17-15.33.22.919436+330 I4009E567             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.24.360386+330 I4577E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.24.364329+330 I4909E490             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.25.131663+330 I5400E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.25.133026+330 I5732E488             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.25.926492+330 I6221E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.25.927721+330 I6553E490             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.27.267106+330 I7044E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.27.270143+330 I7376E567             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.28.395735+330 I7944E331             LEVEL: Error
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-17-15.33.28.400220+330 I8276E490             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-15.33.33.646664+330 E8767E406             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.60.146.125" and Service name/Port number: "30699".

2022-11-17-15.33.33.647667+330 I9174E348             LEVEL: Warning
PID     : 6426                 TID : 139710600894272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrDrdaArShouldDoCR, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-17-19.24.49.825381+330 I9523E387             LEVEL: Error
PID     : 7197                 TID : 139686591321920 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.58802.221117134155
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-17-19.50.11.919250+330 I9911E388             LEVEL: Error
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.50810.221117141141
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 187 and iBytesSent = 0.

2022-11-17-19.50.11.927544+330 I10300E497            LEVEL: Warning
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.50810.221117141141
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-17-19.50.11.928436+330 I10798E484            LEVEL: Warning
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.50810.221117141141
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 34 bytes
192.168.137.133.50810.221117141141

2022-11-17-19.50.11.944131+330 I11283E562            LEVEL: Warning
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.50810.221117141141
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-17-19.50.16.818984+330 E11846E478            LEVEL: Warning
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.34648.221117142016
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.60.146.125" and Service name/Port number: "30699".

2022-11-17-19.50.16.828193+330 I12325E417            LEVEL: Warning
PID     : 10299                TID : 140681977788096 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.34648.221117142016
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-17-20.04.12.505637+330 I12743E387            LEVEL: Error
PID     : 10299                TID : 140682109593408 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.137.133.34648.221117142016
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-17-20.33.20.255200+330 I13131E387            LEVEL: Error
PID     : 15077                TID : 140666186954560 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.217.186.38708.221117145415
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-18-01.44.21.693157+330 I13519E331            LEVEL: Error
PID     : 3181                 TID : 139875819845440 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-01.44.24.721435+330 I13851E331            LEVEL: Error
PID     : 3181                 TID : 139875819845440 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.28.54.265714+330 I14183E331            LEVEL: Error
PID     : 13461                TID : 139880180328256 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.29.04.334253+330 I14515E331            LEVEL: Error
PID     : 13461                TID : 139880180328256 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.29.14.573549+330 I14847E331            LEVEL: Error
PID     : 13461                TID : 139880180328256 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.38.21.879572+330 I15179E331            LEVEL: Error
PID     : 14597                TID : 139988879439680 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.53.20.042545+330 I15511E384            LEVEL: Error
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.56032.221117222148
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 173 and iBytesSent = 0.

2022-11-18-03.53.20.043673+330 I15896E493            LEVEL: Warning
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.56032.221117222148
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-03.53.20.044943+330 I16390E476            LEVEL: Warning
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.56032.221117222148
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 30 bytes
192.168.1.5.56032.221117222148

2022-11-18-03.53.20.051891+330 I16867E556            LEVEL: Warning
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.56032.221117222148
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-03.53.23.644889+330 E17424E472            LEVEL: Warning
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52332.221117222323
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.46.44.42" and Service name/Port number: "30699".

2022-11-18-03.53.23.653794+330 I17897E413            LEVEL: Warning
PID     : 2186                 TID : 140006018512576 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52332.221117222323
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-18-03.55.03.345157+330 I18311E331            LEVEL: Error
PID     : 2935                 TID : 140051091486528 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-03.55.47.634686+330 I18643E331            LEVEL: Error
PID     : 3018                 TID : 140410604480320 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.04.03.807903+330 I18975E384            LEVEL: Error
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.36296.221117222627
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 173 and iBytesSent = 0.

2022-11-18-04.04.03.808603+330 I19360E493            LEVEL: Warning
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.36296.221117222627
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-04.04.03.810365+330 I19854E476            LEVEL: Warning
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.36296.221117222627
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 30 bytes
192.168.1.5.36296.221117222627

2022-11-18-04.04.03.827965+330 I20331E556            LEVEL: Warning
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.36296.221117222627
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.04.07.620753+330 E20888E472            LEVEL: Warning
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.43436.221117223407
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.46.44.42" and Service name/Port number: "30699".

2022-11-18-04.04.07.629698+330 I21361E413            LEVEL: Warning
PID     : 3113                 TID : 139958190864064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.43436.221117223407
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-18-04.42.48.536154+330 I21775E383            LEVEL: Error
PID     : 7863                 TID : 140356884621120 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.41020.221117230632
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-18-04.43.10.786772+330 I22159E331            LEVEL: Error
PID     : 8290                 TID : 139913027438400 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.45.25.102055+330 I22491E331            LEVEL: Error
PID     : 8452                 TID : 140450668250944 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.45.34.336592+330 I22823E331            LEVEL: Error
PID     : 8452                 TID : 140450668250944 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.46.53.226294+330 I23155E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.46.54.913293+330 I23487E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.46.56.521075+330 I23819E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.46.59.532024+330 I24151E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.46.59.533087+330 I24483E425            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-04.46.59.539366+330 I24909E567            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.02.187974+330 I25477E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.02.189183+330 I25809E488            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.03.633331+330 I26298E331            LEVEL: Error
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.03.634382+330 I26630E490            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.07.858675+330 E27121E406            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.61.157.122" and Service name/Port number: "30699".

2022-11-18-04.47.07.866959+330 I27528E348            LEVEL: Warning
PID     : 8778                 TID : 140586788788032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrDrdaArShouldDoCR, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-18-04.47.33.138122+330 I27877E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.34.662156+330 I28209E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.36.511886+330 I28541E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.38.359209+330 I28873E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.38.360559+330 I29205E425            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-04.47.38.367017+330 I29631E567            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.42.329164+330 I30199E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.42.330769+330 I30531E488            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.51.185231+330 I31020E331            LEVEL: Error
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.47.51.186287+330 I31352E490            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.47.54.014963+330 E31843E406            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.60.146.125" and Service name/Port number: "30699".

2022-11-18-04.47.54.015430+330 I32250E348            LEVEL: Warning
PID     : 8955                 TID : 139962895554368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrDrdaArShouldDoCR, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-18-04.49.53.022084+330 I32599E331            LEVEL: Error
PID     : 9338                 TID : 140289021183808 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.37.413138+330 I32931E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.38.901597+330 I33263E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.41.111650+330 I33595E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.44.001363+330 I33927E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.44.002396+330 I34259E425            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-04.52.44.008422+330 I34685E567            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.46.410984+330 I35253E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.46.412266+330 I35585E488            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.48.580979+330 I36074E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.48.582274+330 I36406E490            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.51.273579+330 I36897E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.51.275180+330 I37229E490            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.53.243988+330 I37720E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.53.250724+330 I38052E567            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.57.597004+330 I38620E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.57.598538+330 I38952E488            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.52.59.926275+330 I39441E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.52.59.927564+330 I39773E490            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.53.01.776165+330 I40264E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.53.01.777198+330 I40596E490            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.53.03.780588+330 I41087E331            LEVEL: Error
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-18-04.53.03.787327+330 I41419E567            LEVEL: Warning
PID     : 9748                 TID : 140673503418176 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.55.28.788464+330 I41987E384            LEVEL: Error
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.39596.221117232353
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 231 and iBytesSent = 0.

2022-11-18-04.55.28.788664+330 I42372E493            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.39596.221117232353
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-04.55.28.788807+330 I42866E476            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.39596.221117232353
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 30 bytes
192.168.1.5.39596.221117232353

2022-11-18-04.55.28.804373+330 I43343E558            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.39596.221117232353
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-04.55.31.852118+330 E43902E474            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.60.146.125" and Service name/Port number: "30699".

2022-11-18-04.55.31.852413+330 I44377E413            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-18-05.00.02.943791+330 I44791E384            LEVEL: Error
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 173 and iBytesSent = 0.

2022-11-18-05.00.02.943976+330 I45176E493            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-18-05.00.02.944138+330 I45670E476            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 30 bytes
192.168.1.5.52532.221117232531

2022-11-18-05.00.02.951340+330 I46147E556            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.52532.221117232531
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-18-05.00.08.847912+330 E46704E472            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.38226.221117233008
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.46.44.42" and Service name/Port number: "30699".

2022-11-18-05.00.08.848151+330 I47177E413            LEVEL: Warning
PID     : 10018                TID : 140337797396160 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.1.5.38226.221117233008
HOSTNAME: vishnu-82ey
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.
