
2022-11-16-10.19.27.125416+330 I1E1935               LEVEL: Event
PID     : 12196                TID : 139907384517440 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, RAS/PD component, pdLogInternal, probe:120
START   : New Diagnostic Log file
DATA #1 : Build Level, 248 bytes
Instance "DB2" uses "64" bits and DB2 code release "SQL11056"
with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_13806", "DYN2201171140AMD64_13806", Fix Pack "0".
DATA #2 : System Info, 664 bytes
System: Linux vishnu-pt5599 14 5 x86_64
CPU: total:8 online:8 Cores per socket:4 Threading degree per core:2 SIMD:Y CPU Features:SSE2,SSE3,SSSE3,SSE4,AVX2,AVX512
CPU binding: not in use
CPU cache: L2:1310720 bytes (shared by 2 threads) L3:12582912 bytes (shared by 8 threads)
Physical Memory(MB): total:15736 free:1371
Virtual  Memory(MB): total:15736 free:1371
Swap     Memory(MB): total:0 free:0
Kernel   Params: msgMaxMessageSize:8192 msgMsgMap:16384 msgMaxQueueIDs:32000
                 msgNumberOfHeaders:16384 msgMaxQueueSize:16384
                 msgMaxSegmentSize:16 shmMax:9223372036854775807 shmMin:1
                 shmIDs:4096 shmSegments:4096 semMap:1024000000 semIDs:32000
                 semNum:1024000000 semUndo:1024000000 semNumPerID:32000
                 semOps:500 semUndoSize:20 semMaxVal:32767
                 semAdjustOnExit:32767
Cur cpu time limit (seconds)  = 0xFFFFFFFFFFFFFFFF
Cur file size limit (bytes) = 0xFFFFFFFFFFFFFFFF
Cur data size (bytes)  = 0xFFFFFFFFFFFFFFFF
Cur stack size (bytes)  = 0x0000000000800000
Cur core size (bytes)  = 0x0000000000000000
Cur memory size (bytes) = 0xFFFFFFFFFFFFFFFF
nofiles (descriptors)  = 0x0000000000100000
Cur maximum number of processes = 0x000000000000F42B
Disk: 4K Device Support: NONE

Information in this record is only valid at the time when this file was
created (see this record's time stamp)

2022-11-16-10.19.27.143228+330 I1937E817             LEVEL: Error
PID     : 12196                TID : 139907384517440 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.21.29.636236+330 I2755E817             LEVEL: Error
PID     : 12360                TID : 139988550337344 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.22.07.476779+330 I3573E817             LEVEL: Error
PID     : 12440                TID : 139799956431680 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.22.32.596986+330 I4391E817             LEVEL: Error
PID     : 12508                TID : 140036697506624 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.23.31.332995+330 I5209E817             LEVEL: Error
PID     : 12771                TID : 140705425191744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.23.59.664251+330 I6027E817             LEVEL: Error
PID     : 12837                TID : 140297825403712 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.24.26.612869+330 I6845E817             LEVEL: Error
PID     : 12910                TID : 140292783158080 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, Connection Manager, sqleUCappConnect, probe:4942
MESSAGE : ZRC=0x8005006D=-2147155859=SQLE_CA_BUILT
          "SQLCA has been built and saved in component specific control block."
DATA #1 : SQLCA, PD_DB2_TYPE_SQLCA, 136 bytes
 sqlcaid : SQLCA     sqlcabc: 136   sqlcode: -1013   sqlerrml: 0
 sqlerrmc: 
 sqlerrp : SQLEUAPC
 sqlerrd : (1) 0x00000000      (2) 0x00000000      (3) 0x00000000
           (4) 0x00000000      (5) 0x00000000      (6) 0x00000000
 sqlwarn : (1)      (2)      (3)      (4)        (5)       (6)    
           (7)      (8)      (9)      (10)        (11)     
 sqlstate: 42705

2022-11-16-10.30.05.994326+330 I7663E369             LEVEL: Error
PID     : 13424                TID : 140339793081152 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "" was not found, TCP/IP function "" error 
          return code = "".

2022-11-16-10.30.05.994579+330 I8033E3729            LEVEL: Severe
PID     : 13424                TID : 140339793081152 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x00007FA364C3B415 _Z16sqljcLogCCIErrorP10sqljCmnMgrPKcP12SQLCC_COND_Thllll + 0x1B5
  [1] 0x00007FA364C2E70F _Z16sqljcCommConnectP10sqljCmnMgr + 0x3EF
  [2] 0x00007FA364C2ED08 _Z15sqljcCmnMgrInitP10sqljCmnMgrP17SQLCC_COMHANDLE_TPhmP14db2UCconHandleh24sqljcInvokeCommExitStatePP21sqljcCommexitCommInfoP8s + 0x2F8
  [3] 0x00007FA364D08BB3 _Z20sqljrCreateTransportP14db2UCconHandle + 0xD3
  [4] 0x00007FA364C492BC _Z23sqljrAssociateTransportP14db2UCconHandlePlbP19SQLE_SRVLST_DBENTRYPi + 0x7C
  [5] 0x00007FA364D06335 _Z26sqljrConnectBasedOnCatalogP14db2UCconHandlePibPb + 0x5E5
  [6] 0x00007FA364D07A36 _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 0x726
  [7] 0x00007FA364D08A3A _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 0x7A
  [8] 0x00007FA364CFBCCB _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 0x32B
  [9] 0x00007FA364C144DA _Z20sqlexAppAuthenticateP14db2UCinterface + 0x4FA
  [10] 0x00007FA364CE6996 _Z18sqljrDrdaArConnectP14db2UCinterface + 0x226
  [11] 0x00007FA364BF2F8B _Z16sqleUCdrdaARinitP14db2UCconHandle + 0xFB
  [12] 0x00007FA364BD12F9 sqleUCappConnect + 0x9C9
  [13] 0x00007FA36463D82F _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 0xD2F
  [14] 0x00007FA3645DD7E0 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 0xAA0
  [15] 0x00007FA3645EFF78 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 0x89B8
  [16] 0x00007FA36458D41E SQLDriverConnectW + 0xB3E
  [17] 0x00007FA366047B39 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/lib/python3.9/site-packages/ibm_db.cpython-39-x86_64-linux- + 0x11B39
  [18] 0x000055E6DE7E2E14 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x181E14
  [19] 0x000055E6DE79CCAF _PyObject_MakeTpCall + 0x2DF
  [20] 0x000055E6DE83680A _PyEval_EvalFrameDefault + 0x42A
  [21] 0x000055E6DE7F7663 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x196663
  [22] 0x000055E6DE7F83C4 _PyFunction_Vectorcall + 0x244
  [23] 0x000055E6DE75F58E /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0xFE58E
  [24] 0x000055E6DE7F8284 _PyFunction_Vectorcall + 0x104
  [25] 0x000055E6DE75EAE6 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0xFDAE6
  [26] 0x000055E6DE7F7663 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x196663
  [27] 0x000055E6DE8A445C PyEval_EvalCodeEx + 0x4C
  [28] 0x000055E6DE7F845B PyEval_EvalCode + 0x1B
  [29] 0x000055E6DE8A450B /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x24350B
  [30] 0x000055E6DE8D4F75 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x273F75
  [31] 0x000055E6DE775987 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x114987
  [32] 0x000055E6DE8DAA2F PyRun_SimpleFileExFlags + 0x1BF
  [33] 0x000055E6DE8DB10B Py_RunMain + 0x38B
  [34] 0x000055E6DE8DB309 Py_BytesMain + 0x39
  [35] 0x00007FA367860083 __libc_start_main + 0xF3
  [36] 0x000055E6DE8620A0 /home/local/ZOHOCORP/vishnu-pt5599/Documents/PersonalExpenseTracker/bin/python + 0x2010A0

2022-11-16-10.31.48.778041+330 I11763E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.49.951750+330 I12097E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.51.210925+330 I12431E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.52.772246+330 I12765E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.52.953495+330 I13099E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.53.134606+330 I13433E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.54.222421+330 I13767E333            LEVEL: Error
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-10.31.54.222848+330 I14101E427            LEVEL: Warning
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-10.31.54.223290+330 I14529E569            LEVEL: Warning
PID     : 13582                TID : 140509931406144 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
31198

2022-11-16-10.37.07.690372+330 I15099E335            LEVEL: Error
PID     : 15056                TID : 140099973677888 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-10.39.18.762515+330 I15435E335            LEVEL: Error
PID     : 15056                TID : 140099973677888 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-10.41.29.834405+330 I15771E335            LEVEL: Error
PID     : 15056                TID : 140099973677888 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-10.43.40.906424+330 I16107E335            LEVEL: Error
PID     : 15056                TID : 140099973677888 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-10.59.37.554190+330 I16443E427            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-10.59.37.554782+330 I16871E490            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.01.48.394346+330 I17362E335            LEVEL: Error
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-11.01.48.394675+330 I17698E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.01.59.749937+330 I18191E569            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.02.10.810360+330 I18761E490            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.02.22.278526+330 I19252E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.02.33.540693+330 I19745E490            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.02.44.396360+330 I20236E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.02.55.464999+330 I20729E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.03.06.732376+330 I21222E490            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.03.17.551664+330 I21713E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.03.28.224227+330 I22206E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.05.37.770499+330 I22699E335            LEVEL: Error
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-11.05.37.770928+330 I23035E490            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.07.48.842358+330 I23526E335            LEVEL: Error
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-11.07.48.842768+330 I23862E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.19.892901+330 I24355E492            LEVEL: Warning
PID     : 17981                TID : 140192169128768 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.39.766896+330 I24848E427            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-11.08.39.767280+330 I25276E492            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.40.407440+330 I25769E492            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.48.072704+330 I26262E569            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.48.674396+330 I26832E490            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.08.49.287965+330 I27323E492            LEVEL: Warning
PID     : 19194                TID : 139708830950208 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.09.07.511343+330 I27816E427            LEVEL: Warning
PID     : 19374                TID : 139910517187392 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-11.09.07.511795+330 I28244E492            LEVEL: Warning
PID     : 19374                TID : 139910517187392 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.60.146.125
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-11.09.08.128075+330 I28737E492            LEVEL: Warning
PID     : 19374                TID : 139910517187392 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 14 bytes
169.61.157.122
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-12.33.06.794405+330 I29230E335            LEVEL: Error
PID     : 29895                TID : 140510322434880 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="110".

2022-11-16-13.05.45.204767+330 I29566E387            LEVEL: Error
PID     : 35608                TID : 140677566370624 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.34846.221116073440
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-13.12.53.869265+330 I29954E333            LEVEL: Error
PID     : 37443                TID : 140627920642880 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-13.15.53.398044+330 I30288E333            LEVEL: Error
PID     : 38285                TID : 140201215750976 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-13.16.19.260738+330 I30622E333            LEVEL: Error
PID     : 38569                TID : 140496150082368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-13.16.20.343941+330 I30956E333            LEVEL: Error
PID     : 38569                TID : 140496150082368 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-14.28.50.662076+330 I31290E387            LEVEL: Error
PID     : 40049                TID : 140444755239744 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.60402.221116075245
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-14.53.10.186310+330 I31678E333            LEVEL: Error
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-14.53.18.354509+330 I32012E333            LEVEL: Error
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-14.53.19.968437+330 I32346E333            LEVEL: Error
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-14.53.30.224802+330 I32680E333            LEVEL: Error
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-14.53.30.226441+330 I33014E427            LEVEL: Warning
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-14.53.30.229286+330 I33442E569            LEVEL: Warning
PID     : 47486                TID : 140128455975744 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrConnectBasedOnCatalog, probe:25
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 83 bytes
19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-15.03.50.086232+330 I34012E333            LEVEL: Error
PID     : 49470                TID : 140384544494400 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-15.13.04.467850+330 I34346E387            LEVEL: Error
PID     : 50151                TID : 139867496801088 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.35594.221116093717
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-15.15.07.246428+330 I34734E387            LEVEL: Error
PID     : 50959                TID : 139934981600064 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.57690.221116094308
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-15.16.46.647428+330 I35122E388            LEVEL: Error
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.59540.221116094536
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 323 and iBytesSent = 0.

2022-11-16-15.16.46.647679+330 I35511E497            LEVEL: Warning
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.59540.221116094536
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-15.16.46.649083+330 I36009E482            LEVEL: Warning
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.59540.221116094536
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 32 bytes
192.168.67.33.59540.221116094536

2022-11-16-15.16.46.651019+330 I36492E560            LEVEL: Warning
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.59540.221116094536
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-15.16.48.918823+330 E37053E476            LEVEL: Warning
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.33646.221116094648
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.46.44.42" and Service name/Port number: "30699".

2022-11-16-15.16.48.920934+330 I37530E417            LEVEL: Warning
PID     : 51366                TID : 139956532418304 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.33646.221116094648
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-16-15.22.02.021149+330 I37948E387            LEVEL: Error
PID     : 51366                TID : 139956668207936 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.33646.221116094648
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-15.22.22.024385+330 I38336E333            LEVEL: Error
PID     : 52127                TID : 140708131267392 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-15.25.33.805751+330 I38670E333            LEVEL: Error
PID     : 52720                TID : 140388885504832 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-15.25.39.949303+330 I39004E333            LEVEL: Error
PID     : 52720                TID : 140388885504832 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-15.25.41.935944+330 I39338E333            LEVEL: Error
PID     : 52720                TID : 140388885504832 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-15.29.46.829851+330 I39672E387            LEVEL: Error
PID     : 52968                TID : 139934826120000 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.52924.221116095559
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-15.35.56.422415+330 I40060E333            LEVEL: Error
PID     : 55153                TID : 139883468862272 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-16.25.50.207929+330 I40394E387            LEVEL: Error
PID     : 61466                TID : 140525368857408 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.34848.221116105151
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-16.34.53.683412+330 I40782E387            LEVEL: Error
PID     : 61893                TID : 140352634823488 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.49208.221116105615
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-17.20.07.474240+330 I41170E388            LEVEL: Error
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.41026.221116114811
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 344 and iBytesSent = 0.

2022-11-16-17.20.07.474667+330 I41559E497            LEVEL: Warning
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.41026.221116114811
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:14
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 30 bytes
Client Reroute is starting....

2022-11-16-17.20.07.474910+330 I42057E482            LEVEL: Warning
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.41026.221116114811
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetrySetup, probe:15
DATA #1 : String, 50 bytes
The correlation token of the failed connection is 
DATA #2 : String, 32 bytes
192.168.67.33.41026.221116114811

2022-11-16-17.20.07.476904+330 I42540E560            LEVEL: Warning
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.41026.221116114811
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrListToConnect, probe:20
DATA #1 : String, 40 bytes
Reconnecting to Hostname/IP Address --> 
DATA #2 : String, 12 bytes
169.46.44.42
DATA #3 : String, 45 bytes
Reconnecting to Service name/Port number --> 
DATA #4 : String, 5 bytes
30699

2022-11-16-17.21.15.599316+330 E43101E476            LEVEL: Warning
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.46404.221116115115
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I  Client Reroute successful. Hostname/IP Address: 
          "169.46.44.42" and Service name/Port number: "30699".

2022-11-16-17.21.15.599779+330 I43578E417            LEVEL: Warning
PID     : 66962                TID : 139850468026112 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.46404.221116115115
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrClientReroute, probe:998
DATA #1 : String, 41 bytes
Client Reroute is completed successfully.

2022-11-16-18.11.11.952160+330 I43996E387            LEVEL: Error
PID     : 67796                TID : 140426919486272 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.42840.221116115405
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-18.29.42.047500+330 I44384E387            LEVEL: Error
PID     : 71707                TID : 139850923991872 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.44760.221116124211
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-18.29.59.442651+330 I44772E333            LEVEL: Error
PID     : 73502                TID : 140292056306496 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-18.30.01.289944+330 I45106E333            LEVEL: Error
PID     : 73502                TID : 140292056306496 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-18.31.30.839307+330 I45440E387            LEVEL: Error
PID     : 73653                TID : 140119319888704 PROC : python
INSTANCE: DB2                  NODE : 000            DB   : BLUDB   
APPID   : 192.168.67.33.37486.221116130008
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlccSSLSocketWrite, probe:10
MESSAGE : sendBufsize = 25 and iBytesSent = 0.

2022-11-16-18.31.45.056906+330 I45828E333            LEVEL: Error
PID     : 73901                TID : 140218977964864 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-18.32.18.175192+330 I46162E333            LEVEL: Error
PID     : 74014                TID : 139768205939520 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-18.46.12.545381+330 I46496E333            LEVEL: Error
PID     : 75965                TID : 140217567540032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".

2022-11-16-18.46.13.631566+330 I46830E333            LEVEL: Error
PID     : 75965                TID : 140217567540032 PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: vishnu-pt5599
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="4".
